<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Casino</name>
   <tag></tag>
   <elementGuidId>d9e88412-6a21-46e9-8136-1d52e6323ebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GAMING</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='GAMING']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>47692abd-77da-4ca7-938e-5974ed124cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GAMING</value>
      <webElementGuid>f27b13be-29c7-4174-9e2b-09fcdc2f0a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/d/casino/casino</value>
      <webElementGuid>649cd853-11cf-4fee-8bf8-c565b68da7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>024ffeb1-96a7-4ec8-855c-59afd13b17cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Casino</value>
      <webElementGuid>6ff25701-fc79-4178-9096-20c4c50c7f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtml</name>
      <type>Main</type>
      <value>GAMING</value>
      <webElementGuid>cac64dfb-e262-44b8-af7f-0ccbbdba5637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                               Casino
                                                            </value>
      <webElementGuid>ea0eb910-af1a-46a2-a38b-17439ee70f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GAMING&quot;)</value>
      <webElementGuid>4124beb3-8fde-49b0-96a5-115dfd605191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='GAMING']</value>
      <webElementGuid>5c0c9759-4d36-41b3-b96c-5beb650a7b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ssc-mgr-GAMING']/a</value>
      <webElementGuid>25d1221f-7e7e-42e7-9862-4dd79e17dead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Casino')])[2]</value>
      <webElementGuid>fe2bdf3b-88c6-4e0f-88e7-8ddde7464773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[1]/following::a[1]</value>
      <webElementGuid>c515b71b-88cc-4771-9af7-bb5bda2ee984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sportsbook'])[1]/following::a[2]</value>
      <webElementGuid>bc6792eb-c59f-4146-8ca7-f95694c7e194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slots'])[1]/preceding::a[1]</value>
      <webElementGuid>0336eec0-bb0c-425d-9bc7-4e8e17e68bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Casino'])[1]/preceding::a[2]</value>
      <webElementGuid>e5d738eb-e002-4e5e-8fa9-c61a7202948e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://haboom.com/d/casino/casino')])[2]</value>
      <webElementGuid>f64ce8a8-60af-492c-8a6b-51e656ffe97f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>0f8ed66f-9488-4994-93d7-53162debeb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'GAMING' and @href = 'https://haboom.com/d/casino/casino' and @title = 'Casino' and (text() = '
                                                               Casino
                                                            ' or . = '
                                                               Casino
                                                            ')]</value>
      <webElementGuid>f16e1ff6-ff68-4398-9614-540c06d3369c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
