<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Exchange</name>
   <tag></tag>
   <elementGuidId>adbdfaf7-cd52-40ed-b623-21fb2770c731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EXCHANGE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='EXCHANGE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>649d8b9a-e85d-4c3e-922b-d05f6d371fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EXCHANGE</value>
      <webElementGuid>def9ce8a-90a0-43ac-979e-9ccfc9d01b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/d/exchange</value>
      <webElementGuid>cc1164d3-fcb4-4d6f-9f54-56353c2e7dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>724cc4d0-6d26-4071-835f-47a9bb1514d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Exchange</value>
      <webElementGuid>2291702e-348b-428c-b8aa-ae3ea0dcfac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtml</name>
      <type>Main</type>
      <value>EXCHANGE</value>
      <webElementGuid>6ed4ed68-1f8d-4937-b49b-5f39a2bfe578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                               Exchange
                                                            </value>
      <webElementGuid>e350bce8-492c-4dee-92ad-e9e67ac0e895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EXCHANGE&quot;)</value>
      <webElementGuid>50a68af4-e0c1-428c-b870-30be9e842e0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='EXCHANGE']</value>
      <webElementGuid>0e0c5c53-de30-4a77-ab8f-da91ed609200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ssc-pn']/li[2]/a</value>
      <webElementGuid>7d54b000-5ec4-497f-90d3-1d5f97f72183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Exchange')]</value>
      <webElementGuid>cfbe0b60-73a3-4c85-962c-c6d8c70944b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>dd35ed04-ae0d-449a-89dd-fdb91a363bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sportsbook'])[1]/preceding::a[1]</value>
      <webElementGuid>55673fdb-61d5-4767-b0d7-44c54046a7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[1]/preceding::a[2]</value>
      <webElementGuid>c4729f68-38e7-4563-ac64-29be89fa0b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Exchange']/parent::*</value>
      <webElementGuid>92afc52f-44be-48cd-af2a-f6e3d48d315e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://haboom.com/d/exchange')])[2]</value>
      <webElementGuid>4b185bb9-7ea9-49c3-b424-49869c1c008e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>6339ba52-e280-417c-b181-8c49df387fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'EXCHANGE' and @href = 'https://haboom.com/d/exchange' and @title = 'Exchange' and (text() = '
                                                               Exchange
                                                            ' or . = '
                                                               Exchange
                                                            ')]</value>
      <webElementGuid>f369064c-9e75-44ff-bd98-d404ec280904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
